### PR TITLE
Got a general layout done

### PR DESCRIPTION
**Pull request by ghost**
Just need to add a few more pieces, but the general set is done. Once I figure out a way to do a simplistic layout for all the information then just need to build a class and list to store the information for the user.

### CODE REVIEW

**Comment by ThorinSchmidt** [comment]
I don't have it uploaded yet,  but I've got a mostly working equipment
class.

I'll commit and do a pull request later today.

Thorin Schmidt
-sent from smartphone

**Comment by ThorinSchmidt** [comment]
so I pushed my changes to my personal fork, and am going to submit a
request momentarily.  After that, I'll delete my local fork, then re-make
it based off of the main branch.  That should make things a little
smoother.  btw, have you tried using GIT through android studio?
The VCS menu has full git integration if you install the plugin..



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Thanks,


---------------------------------------------------------------------
*Mr. Thorin Schmidt*
PLTW/CS Instructor
Lewis & Clark Career Center
2400 Zumbehl Rd
St. Charles, MO
 https://www.linkedin.com/in/thorinschmidt
 http://computerinformationsquad.blogspot.com/

**Comment by ghost** [comment]
I couldn't figure out how to get the VCS working in Android Studio though I do know what you are talking about. That's why I have been doing everything from the GIT Shell. I also would need to set that up on the tech computer if I were to do that.

**Comment by ThorinSchmidt** [comment]
Odd, it just automatically worked for me on my laptop...


Thanks,


---------------------------------------------------------------------
*Mr. Thorin Schmidt*
PLTW/CS Instructor
Lewis & Clark Career Center
2400 Zumbehl Rd
St. Charles, MO
 https://www.linkedin.com/in/thorinschmidt
 http://computerinformationsquad.blogspot.com/

**Comment by ghost** [comment]
I might just be too much of a scrub for it. Will look further into how to do it correctly because I know whenever I try it always ran into some error when I tried it.

**Comment by ThorinSchmidt** [comment]
Oh.  I had to turn ssl verify off with gitbash... Maybe that was it.  No
biggie though.  Back to the other question.  Was the player manual button
just a placeholder,  or should we use it to link the players to the online
pdf? Or possibly the m&m website?

Thorin Schmidt
-sent from smartphone

**Comment by ghost** [comment]
I was going to link it to the pdf file itself so it's always there on hand in case they don't have a paper copy.
I was trying to figure out how to use the menu at the top and have that be a way to link to the m&m website as well as a help option to be on the safe side. I also left room to the left of the continue character button if we want to have a multiple character save system. I don't think it would be too hard to rig the button to read the currently selected character from a list to then pull that information up. It's just a thought still.

**Comment by ThorinSchmidt** [comment]
That sounds fine to me.  Then i would suggest that we add an "M&M
Companion" button as well. I've incorporated most of the content of that
book as well.

Thorin Schmidt
-sent from smartphone

**Pull request merged**
